### ISSUE TITLE
Result List

### ISSUE THREAD

**Issue by Efendi5** [Efendi5/capstone-project#1]
## Result List

Value Proposition

- As a User
- I want to see the results
- to be able to know the winner and to decide play again or move to menu.

## Description

![Image](https://user-images.githubusercontent.com/123765768/227647238-64a8681f-017c-42cc-9203-6936d61b77be.png)

## Acceptance criteria

- [ ] First results from first round shows up 
- [ ] You can Play Total 3 Rounds to decide who is the winner of the complete match
- [ ] result of both players shows up, every round result is till the end available so after 3 rounds the result is evaluated in its entirety, whoever has the most points at the end wins
- [ ] its possible to click go back Home with home button
- [ ] its possible to click play again with "game" button
- [ ] you can see the complete score 
- [ ] the page is always visible after 3 rounds

## Tasks

- [ ] Global Styles
- [ ] component/ result list
- [ ] component/ result
- [ ] component/ user
- [ ] component/ score
- [ ] component/ play again Button
- [ ] component/ Go back Home Button
- [ ] Add to App

**Comment by PReichetanz** [comment]
Agreed with @salaos!

Two more things: 
- Please mention (in the description of the ACs) when this page is visible. I guess it is after the last question has been answered, but that's not clear from what you have written.
- Value Proposition: be more concise here. 
```
As a user
I want to see the results
to be able know the winner and to decide what to do next.
```

**Comment by Efendi5** [comment]
thank you for your help !
