### ISSUE TITLE
SignUp

### ISSUE THREAD

**Issue by Efendi5** [Efendi5/capstone-project#13]
## Value Proposition

**As a** ... User 
**I want to** ... SignUp
**so that** ... I have an account to play the game 
​

## Description

<img width="296" alt="Bildschirmfoto 2023-04-14 um 11 35 42" src="https://user-images.githubusercontent.com/123765768/232008000-67f78541-953e-4b55-9f48-bb31b4321355.png">

​

## Acceptance Criteria

- [ ] On the Top you can see the Logo and a small text
- [ ] In the middle you can see choose a name 
- [ ] After this you can Sign Up with your name
      ​

## Tasks

- [ ] Global Styles
- [ ] component Logo
- [ ] component Username
- [ ] component SignUp
- [ ] create function for SignUp, UserName
- [ ] Add to App

**Comment by PReichetanz** [comment]
Hi Efendi,
the ACs should describe what happens, not was is visible alone (and can be seen in the scribble).
Answer questions like
- what happens if I click on Sign Up? Where am I redirected?
- What happens if I have the wrong user name?

Besides: is it a sign up or only a sign in because the possible usernames which are allowed to log in are predefined?

**Comment by Efendi5** [comment]
change it :)

**Comment by PReichetanz** [comment]
> change it :)

But you did not answer the questions: there should be something like "If the user clicks on sign up, he is redirected to..." or "If the wrong user name is used, an error message occurs."

Please adapt your wireframe as well to show how the error message and redirects look like.
