### ISSUE TITLE
User Stroy 3 ->Card with questions, Timeline, 4 possible answers and Next Button

### ISSUE THREAD

**Issue by Efendi5** [Efendi5/capstone-project#2]
## Card with questions, Timeline, 4 possible answers and Next Button

Value Proposition

- As a User
- I want to a question, a time line, 1 correct answer 3 false answers and the next Button
- to be able to push next Button after pushing one of the 4 answers, also see under the users each points

## Description

![Image](https://user-images.githubusercontent.com/123765768/227486375-b8319052-4b69-4021-8369-70d99566fb12.png)

## Acceptance criteria

- [ ] First question appears 
- [ ] In total 3 questions
- [ ] TimeLine expires 
- [ ] After clicking one answer 
- [ ] the correct/wrong answers are displayed
- [ ] you can see if you get a point or not, the representation can be seen under the user profile
- [ ] Button for next questions shows up

## Tasks

- [ ] Global Styles
- [ ] component/QuizCard
- [ ] component/ Timeline
- [ ] component/ Points
- [ ] component/ AnswerButton
- [ ] Write Tests
- [ ] fetch random question from db.js
- [ ] create function for timeLine 
- [ ] fetch answers related to question
- [ ] next Button shows up
- [ ] Add to App

**Comment by Gblur** [comment]
```import {useEffect, useState, useRef} from "react";
import styled from "styled-components";
import {questions} from "../../../DB/data";

export default function AnswerButtons({
  points1,
  setPoints1,
  selectedAnswer,
  setSelectedAnswer,
  isDisabled,
  setIsDisabled,
  setIsTimerPaused,
  timeLeft,
  index,
}) {
  const [answerIndex, setAnswerIndex] = useState(null);
  const currentQuestion = questions[index];
  const getIndexOfCorrectAnswer = currentQuestion.answers.indexOf(
    currentQuestion.correctAnswer
  );

  const handleAnswerClick = (answer, index) => {
    setAnswerIndex(() => index);
    setIsDisabled(true);
    setIsTimerPaused(true);

    if (answer === currentQuestion.correctAnswer) {
      setPoints1(points1 + 1);
      setSelectedAnswer("correct");
    } else {
      setSelectedAnswer("incorrect");
      setTimeout(() => {
        setAnswerIndex(getIndexOfCorrectAnswer);
        setSelectedAnswer("correct");
      }, 500);
    }
  };

  const handleTimer = (index) => {
    if (timeLeft === 0) {
      setAnswerIndex(index);
      setSelectedAnswer("correct");
    }
  };
  useEffect(() => {
    handleTimer(getIndexOfCorrectAnswer);
  }, [timeLeft]);

  return (
    <StyledDiv>
      {currentQuestion.answers.map((answer, index) => {
        switch (selectedAnswer && true) {
          // if selected answer is correct then classname = "correct"
          // should only be the card that was clicked
          case selectedAnswer === "correct" && answerIndex === index:
            return (
              <StyledButton
                disabled={isDisabled}
                type="button"
                key={answer}
                onClick={() => handleAnswerClick(answer, index)}
                className="correct"
              >
                <strong>{answer}</strong>
              </StyledButton>
            );
          // answer is incorrect then classname incorrect
          case selectedAnswer === "incorrect" && answerIndex === index:
            return (
              <StyledButton
                disabled={isDisabled}
                type="button"
                key={answer}
                onClick={() => handleAnswerClick(answer, index)}
                className="incorrect"
              >
                <strong>{answer}</strong>
              </StyledButton>
            );
          // default has no class
          default:
            return (
              <StyledButton
                disabled={isDisabled}
                type="button"
                key={answer}
                onClick={() => handleAnswerClick(answer, index)}
                className=""
              >
                <strong>{answer}</strong>
              </StyledButton>
            );
        }
      })}
    </StyledDiv>
  );
}

export const StyledButton = styled.button`
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 30px;
  width: 170px;
  height: 80px;
  background-color: #60a5bf;
  border-radius: 20px;
  color: #ffffff;
  font-size: 14px;
  cursor: pointer;
  margin-block: 5px;
  box-shadow: 0 8px 20px rgba(0, 0, 0, 0.5);

  &.correct {
    background-color: green;
    color: white;
  }

  &.incorrect {
    background-color: red;
    color: white;
  }
`;

export const StyledDiv = styled.div`
  display: grid;
  max-width: 400px;
  grid-template-columns: repeat(2, 1fr);
  grid-template-rows: repeat(2, 1fr);
  gap: 15px;
  margin-top: 25px;
  align-items: center;

  button:nth-child(1) {
    grid-row: 1 / span 1;
    grid-column: 1 / span 1;
  }

  button:nth-child(2) {
    grid-row: 1 / span 1;
    grid-column: 2 / span 1;
  }

  button:nth-child(3) {
    grid-row: 2 / span 1;
    grid-column: 1 / span 1;
  }

  button:nth-child(4) {
    grid-row: 2 / span 1;
    grid-column: 2 / span 1;
  }
`;
```
