### ISSUE TITLE
QuizCard Page

### ISSUE THREAD

**Issue by Efendi5** [Efendi5/capstone-project#3]
## Card with questions and timeline

Value Proposition

- As a User
- I want to have a question in the quizCard a timeline and 4 possible answer options
- to be able to in order to choose an answer before timeline ends

## Description

![Image](https://user-images.githubusercontent.com/123765768/227646881-ceb8b62f-3df4-42fb-9547-0f9b65728389.png)

## Acceptance criteria

- [ ] First question appears in the quizcard
- [ ] TimeLine expires you have 30 sec to choose one answer
- [ ] you can see under each user the current still empty points
- [ ] 4 possible answer options appears and you can choose one of them
- [ ] after this you switch to the next quizcard wird next question

## Tasks

- [ ] Global Styles
- [ ] component/QuizCard
- [ ] component/ Timeline
- [ ] component/ points
- [ ] component/ User
- [ ] component/ AnswerButton
- [ ] Write Tests for quizcard, timeline, answerbutton, nextbutton, User, UserPoints, Header
- [ ] create function for timeLine 
- [ ] fetch answers related to question
- [ ] next Button hidden 
- [ ] Add to App
