### ISSUE TITLE
Start Page

### ISSUE THREAD

**Issue by Efendi5** [Efendi5/capstone-project#4]
## Next Button Shows Up to start Quiz

Value Proposition

- As a User 
- I want to see a button
- in order to start the quiz

## Description
![Image](https://user-images.githubusercontent.com/123765768/227478184-86ab835e-dc35-4421-afa0-ee05d3fa536a.png)

## Acceptance criteria

- [ ] QuizCard with title "Battle Quiz" shows up
- [ ] After pushing Button "next" you can start the quiz, and the first question shows up
- [ ] In the Header is shown both Users and the Logo 

## Tasks:

- [ ] Global Styles
- [ ] component/QuizCard
- [ ] component/ User
- [ ] component/ Logo
- [ ] component/Button
- [ ] Write Tests
- [ ] Add to App
