### ISSUE TITLE
Question options

### ISSUE THREAD

**Issue by Efendi5** [Efendi5/capstone-project#5]
## Value Proposition

**As a** User  
**I want to** see 5 questions to choose 3 of them 
**so that** both of users get questions to answer them
​

## Description

​
<img width="329" alt="Bildschirmfoto 2023-03-24 um 23 28 31" src="https://user-images.githubusercontent.com/123765768/227654838-487e65fe-a22a-4abe-8086-66dcc95ac01c.png">

## Acceptance Criteria

- [ ] in the headline the task is explained what each user must do
- [ ] Both of Users can separately choose 3 of 5 questions
- [ ] both of Users get the 3 questions selected of the other
- [ ] while the timeline rolls down both of the Users have to choose the 3 questions
- [ ] when the user don't choose the 3 questions before the timeline is over the system will automatically choose 3      ​

## Tasks

- [ ] Global Styles
- [ ] component/QuizCard
- [ ] component/ Timeline
- [ ] component/ users
- [ ] component/headline
- [ ] component/ hiddenButton
- [ ] create function for timeLine
- [ ] next Button hidden
- [ ] Write Tests for quizcards, timeline, hidden nextbutton
- [ ] fetch random question from db.js
- [ ] Add to App
