### ISSUE TITLE
Next Button Shows Up to switch to main part of quiz

### ISSUE THREAD

**Issue by Efendi5** [Efendi5/capstone-project#6]
## Value Proposition

**As a**  User
**I want to** see a button
**so that** to start the quiz

## Description

<img width="327" alt="Bildschirmfoto 2023-03-24 um 23 42 39" src="https://user-images.githubusercontent.com/123765768/227656590-79919544-a820-449b-81b0-b3ee0747959d.png">
​

## Acceptance Criteria

- [ ] After choosing 3 questions of 5 or timeline is finished next button appears
- [ ] each of the users can now move to the main part of the quiz
      ​

## Tasks

- [ ]  Global Styles
- [ ]  component/Button
- [ ] Write Tests
- [ ]  Add to App
