### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by Efendi5** [Efendi5/capstone-project#7]
## Value Proposition

**As a** User 
**I want to** see the main menu
**so that** I can click the play button
​

## Description

<img width="370" alt="Bildschirmfoto 2023-03-25 um 00 00 47" src="https://user-images.githubusercontent.com/123765768/227658750-077a5eaa-7fec-4158-aa74-19841fc7aa0a.png">

## Acceptance Criteria

- [ ]  The User can see his Profil in the middle of the display(with name and a smiley)
- [ ]  on the top the user can see the logo of the game
- [ ]  on the bottom the user have a navbar to click for playing a quiz game
      ​

## Tasks

- [ ] Global Styles
- [ ] component/ header
- [ ] comonent/ navbar with play 
- [ ] component/ Link
- [ ] Write Tests for navbar
- [ ] Add to App
